import { RtpCapabilities } from '../../RtpParameters';
/**
 * Extract RTP capabilities.
 *
 * @param {Object} sdpObject - SDP Object generated by sdp-transform.
 */
export declare function extractRtpCapabilities({ sdpObject }: {
    sdpObject: any;
}): RtpCapabilities;
/**
 * Extract DTLS parameters.
 *
 * @param {Object} sdpObject - SDP Object generated by sdp-transform.
 *
 * @returns {RTCDtlsParameters}
 */
export declare function extractDtlsParameters(param: {
    sdpObject: any;
}): any;
/**
 * Get RTCP CNAME.
 *
 * @param {Object} offerMediaObject - Local SDP media Object generated by sdp-transform.
 */
export declare function getCname(param: {
    offerMediaObject: any;
}): string;
/**
 * Apply codec parameters in the given SDP m= section answer based on the
 * given RTP parameters of an offer.
 *
 * @param {RTCRtpParameters} offerRtpParameters
 * @param {Object} answerMediaObject
 */
export declare function applyCodecParameters({ offerRtpParameters, answerMediaObject }: {
    offerRtpParameters: any;
    answerMediaObject: any;
}): void;
//# sourceMappingURL=commonUtils.d.ts.map