/**
 * Extract plain RTP parameters from a SDP.
 *
 * @param {Object} sdpObject - SDP Object generated by sdp-transform.
 * @param {String} kind - Media type.
 *
 * @returns {Object} with ip (String), ipVersion (4 or 6 Number) and port (Number).
 */
exports.extractPlainRtpParameters = function({ sdpObject, kind })
{
	const mediaObject = (sdpObject.media || [])
		.find((m) => m.type === kind);

	if (!mediaObject)
		throw new Error(`m=${kind} section not found`);

	const connectionObject = mediaObject.connection || sdpObject.connection;

	return {
		ip        : connectionObject.ip,
		ipVersion : connectionObject.version,
		port      : mediaObject.port
	};
};

/**
 * Get RTP encodings.
 *
 * @param {Object} sdpObject - SDP Object generated by sdp-transform.
 * @param {String} kind - Media type.
 *
 * @returns {Array<RTCRtpEncodingParameters>}
 */
exports.getRtpEncodings = function({ sdpObject, kind })
{
	const mediaObject = (sdpObject.media || [])
		.find((m) => m.type === kind);

	if (!mediaObject)
		throw new Error(`m=${kind} section not found`);

	const ssrcCnameLine = (mediaObject.ssrcs || [])[0];
	const ssrc = ssrcCnameLine ? ssrcCnameLine.id : null;

	if (ssrc)
		return [ { ssrc } ];
	else
		return [];
};
