import { RtpEncodingParameters } from '../../RtpParameters';
/**
 * Extract plain RTP parameters from a SDP.
 *
 * @param {Object} sdpObject - SDP Object generated by sdp-transform.
 * @param {String} kind - Media type.
 *
 * @returns {Object} with ip (String), ipVersion (4 or 6 Number) and port (Number).
 */
export declare function extractPlainRtpParameters({ sdpObject, kind }: {
    sdpObject: any;
    kind: string;
}): any;
/**
 * Get RTP encodings.
 *
 * @param {Object} sdpObject - SDP Object generated by sdp-transform.
 * @param {String} kind - Media type.
 */
export declare function getRtpEncodings({ sdpObject, kind }: {
    sdpObject: any;
    kind: string;
}): RtpEncodingParameters[];
//# sourceMappingURL=plainRtpUtils.d.ts.map