import { RtpEncodingParameters } from '../../RtpParameters';
/**
 * Get RTP encodings.
 *
 * @param {Object} offerMediaObject - Local SDP media Object generated by sdp-transform.
 * @param {MediaStreamTrack} track
 */
export declare function getRtpEncodings({ offerMediaObject, track }: {
    offerMediaObject: any;
    track: MediaStreamTrack;
}): RtpEncodingParameters[];
/**
 * Adds multi-ssrc based simulcast into the given SDP media section offer.
 *
 * @param {Object} offerMediaObject - Local SDP media Object generated by sdp-transform.
 * @param {MediaStreamTrack} track
 * @param {Number} numStreams - Number of simulcast streams.
 */
export declare function addLegacySimulcast({ offerMediaObject, track, numStreams }: {
    offerMediaObject: any;
    track: MediaStreamTrack;
    numStreams: number;
}): void;
//# sourceMappingURL=planBUtils.d.ts.map