import { RtpEncodingParameters } from '../../RtpParameters';
/**
 * Get RTP encodings.
 *
 * @param {Object} offerMediaObject - Local SDP media Object generated by sdp-transform.
 */
export declare function getRtpEncodings({ offerMediaObject }: {
    offerMediaObject: any;
}): RtpEncodingParameters[];
/**
 * Adds multi-ssrc based simulcast into the given SDP media section offer.
 *
 * @param {Object} offerMediaObject - Local SDP media Object generated by sdp-transform.
 * @param {Number} numStreams - Number of simulcast streams.
 */
export declare function addLegacySimulcast({ offerMediaObject, numStreams }: {
    offerMediaObject: any;
    numStreams: number;
}): void;
//# sourceMappingURL=unifiedPlanUtils.d.ts.map